# Generated by Django 5.0.6 on 2026-07-27 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_waitlist',
            field=models.BooleanField(default=True, help_text='When full, place further sign-ups on a waitlist.'),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum confirmed attendees. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Last moment attendees can register. Defaults to the event start time.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp_enabled',
            field=models.BooleanField(default=False, help_text='Allow attendees to RSVP / reserve tickets on SankofaX.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, help_text='External ticketing link. Leave blank to use on-platform RSVP instead.'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Number of seats / tickets reserved.')),
                ('note', models.CharField(blank=True, help_text='Optional message to the organizer (e.g. accessibility needs).', max_length=300)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='confirmed', max_length=12)),
                ('ticket_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='events_even_event_i_cdd3f8_idx'), models.Index(fields=['attendee', 'status'], name='events_even_attende_b016bb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('event', 'attendee'), name='uniq_active_registration_per_event_attendee'),
        ),
    ]
