# Generated by Django 5.0.6 on 2026-07-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_companyprofile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji or icon name shown with the badge, e.g. ♀ or a lucide icon name', max_length=40)),
                ('color', models.CharField(blank=True, help_text='Optional hex colour for the badge, e.g. #B5813B', max_length=7)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = shown first')),
            ],
            options={
                'verbose_name': 'Identity Badge',
                'verbose_name_plural': 'Identity Badges',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, help_text='Ownership / identity badges, e.g. Women-Owned, Black-Owned, LGBTQ+-Owned', related_name='companies', to='profiles.identitybadge'),
        ),
    ]
