# Generated by Django 5.0.6 on 2026-07-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_identitybadge_companyprofile_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='founder_story',
            field=models.TextField(blank=True, help_text="The founder's journey — how and why the business started. Shown on the business profile."),
        ),
    ]
