# Generated by Django 5.0.6 on 2026-07-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_companyprofile_founder_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='services',
            field=models.TextField(blank=True, help_text='Comma-separated list of services offered'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
