# Generated by Django 5.0.6 on 2026-07-26 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_companyprofile_facebook_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='verification_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the current tier expires and needs re-verification.', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='verification_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unverified'), (1, 'Basic — Automated checks'), (2, 'Verified — Documents'), (3, 'Certified — Partner-certified')], default=0, help_text='Current verification tier. Granted automatically (Basic) or by admin review (Verified/Certified).'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the current verification tier was granted.', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Kept in sync with verification_level (True when level ≥ Basic).'),
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_level', models.PositiveSmallIntegerField(choices=[(0, 'Unverified'), (1, 'Basic — Automated checks'), (2, 'Verified — Documents'), (3, 'Certified — Partner-certified')])),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('documents', models.FileField(blank=True, help_text='Ownership / registration documents (required for Verified and Certified).', null=True, upload_to='verifications/')),
                ('note', models.TextField(blank=True, help_text="Owner's note to the reviewer.")),
                ('admin_notes', models.TextField(blank=True, help_text='Reviewer notes / reason — shown to the business owner.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='profiles.companyprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
