# Generated by Django 5.0.6 on 2026-07-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_backfill_verification_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='verification_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unverified'), (1, 'Basic (Automated)'), (2, 'Verified (Documents)'), (3, 'Certified (Partner)')], default=0, help_text='Current verification tier. Granted automatically (Basic) or by admin review (Verified/Certified).'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='requested_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unverified'), (1, 'Basic (Automated)'), (2, 'Verified (Documents)'), (3, 'Certified (Partner)')]),
        ),
    ]
