# Generated by Django 5.0.6 on 2026-07-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminuserproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Company User',
                'verbose_name_plural': 'Company Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='RegularUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Regular User',
                'verbose_name_plural': 'Regular Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.AlterModelOptions(
            name='adminuserproxy',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('business_owner', 'Business Owner'), ('moderator', 'Moderator'), ('staff', 'Staff'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='visitor', max_length=20),
        ),
    ]
