# Generated by Django 5.0.6 on 2026-07-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyuserproxy_regularuserproxy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuserproxy',
            options={'verbose_name': 'Company Account', 'verbose_name_plural': 'Company Accounts'},
        ),
        migrations.AlterModelOptions(
            name='regularuserproxy',
            options={'verbose_name': 'General User', 'verbose_name_plural': 'General Users'},
        ),
    ]
