# Generated by Django 5.0.6 on 2026-07-27 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_listing_business_type'),
        ('marketplace', '0001_initial'),
        ('profiles', '0008_alter_companyprofile_verification_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('shipping_address', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='profiles.companyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='0 = free booking request (customer pays nothing online).', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_virtual', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, help_text='City or venue for in-person services.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookable_services', to='profiles.companyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('service_name', models.CharField(max_length=200)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='profiles.companyprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='marketplace.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='marketplace_buyer_i_dfa750_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'status'], name='marketplace_company_5e3482_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['customer', '-created_at'], name='marketplace_custome_ac1c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['company', 'status'], name='marketplace_company_1af017_idx'),
        ),
    ]
