# Generated by Django 5.0.6 on 2026-07-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='default_og_image',
            field=models.ImageField(blank=True, help_text='Default social share image (1200×630px recommended)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_search_console_code',
            field=models.CharField(blank=True, help_text='Google Search Console verification meta content value', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, help_text='Google Tag Manager ID — e.g. GTM-XXXXXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='GA4 Measurement ID — e.g. G-XXXXXXXXXX (leave blank if using GTM)', max_length=30),
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('browser', models.CharField(blank=True, max_length=60)),
                ('browser_ver', models.CharField(blank=True, max_length=20)),
                ('os', models.CharField(blank=True, max_length=60)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('other', 'Other')], default='other', max_length=10)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='core_pagevi_timesta_757ebb_idx'), models.Index(fields=['browser'], name='core_pagevi_browser_174165_idx'), models.Index(fields=['country'], name='core_pagevi_country_87e64d_idx'), models.Index(fields=['path'], name='core_pagevi_path_582912_idx')],
            },
        ),
    ]
