# Generated by Django 5.0.6 on 2026-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_pageview_sitesetting_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_address',
            field=models.CharField(blank=True, help_text='Physical or mailing address', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='e.g. +1 (800) 726-5632', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='https://instagram.com/yourhandle'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL (iframe src from maps.google.com → Share → Embed a map)', max_length=1000),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='response_time',
            field=models.CharField(blank=True, default='Within 24–48 hours', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='https://x.com/yourhandle'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
