# Generated by Django 5.0.6 on 2026-07-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_contact_social_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='map_embed_url',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='Google Maps → Share → Embed a map → paste the full &lt;iframe&gt; code here'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_address',
            field=models.CharField(blank=True, help_text='e.g. 123 Main St, Nairobi, Kenya', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='e.g. +1 (800) 726-5632 or +880 1711-000000', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.facebook.com/sankofax'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.instagram.com/sankofax — footer icons will appear when URLs are added'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.linkedin.com/company/sankofax'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='response_time',
            field=models.CharField(blank=True, default='Within 24–48 hours', help_text='e.g. Within 24–48 hours', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.tiktok.com/@sankofax'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='e.g. https://x.com/sankofax'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.youtube.com/@sankofax'),
        ),
    ]
