# Generated by Django 5.0.6 on 2026-07-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_map_embed_to_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_embed_code',
            field=models.TextField(blank=True, help_text='Footer Instagram feed. Get an embed code from snapwidget.com or lightwidget.com (connect your Instagram there, copy the <iframe> embed) and paste it here. Leave blank to show the default placeholder tiles.'),
        ),
    ]
