# Generated by Django 5.0.6 on 2026-08-03 10:47

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_legal_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(blank=True, default='The Global Black & African Business Directory', max_length=140)),
                ('hero_title', models.CharField(blank=True, default='The Global Directory for', help_text='First line of the hero headline (shown in white).', max_length=200)),
                ('hero_title_highlight', models.CharField(blank=True, default='Black & African-Owned Businesses', help_text='Second line of the hero headline (shown in the accent colour).', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='From Lagos to London, Nairobi to New Orleans — we’re uniting the global African diaspora through visibility, community, and commerce.')),
                ('hero_popular_searches', models.CharField(blank=True, default='Restaurants, Wellness, Tech Companies, Therapists, Creatives, Hair & Beauty', help_text='Comma-separated quick-search chips shown under the hero search bar.', max_length=300)),
                ('why_list_title', models.CharField(blank=True, default='Why List Your Brand?', max_length=200)),
                ('why_list_subtitle', models.TextField(blank=True, default='Getting listed on SankofaX instantly places your brand in front of a global audience actively looking to support Black and African-owned businesses.')),
                ('why_list_benefits', models.JSONField(blank=True, default=apps.core.models._default_benefits, help_text='List of {"title", "desc"} cards. Icons are fixed in the design; edit the text here.')),
                ('mission_title', models.CharField(blank=True, default='Our Mission', max_length=120)),
                ('mission_body', models.TextField(blank=True, default='SankofaX exists to amplify the reach, recognition, and resilience of Black-owned businesses across the globe — because we believe that economic liberation is the foundation of cultural empowerment, and connection is where it begins.')),
                ('vision_title', models.CharField(blank=True, default='Our Vision', max_length=120)),
                ('vision_body', models.TextField(blank=True, default='To become the largest, most inclusive digital directory for Black-owned businesses across the diaspora — a place where heritage, innovation, and community come together to thrive.')),
                ('pricing_title', models.CharField(blank=True, default='Fair Pricing for a Global Community', max_length=200)),
                ('pricing_subtitle', models.TextField(blank=True, default='We recognize the economic differences between regions, and we believe equitable access is non-negotiable. That’s why we offer tiered pricing.')),
                ('pricing_note', models.TextField(blank=True, default='Not sure which region you fall into? We’ll verify your location at signup and apply the appropriate rate automatically.')),
                ('cta_title', models.CharField(blank=True, default='Join the Directory. Be Seen. Be Supported. Be SankofaX.', max_length=250)),
                ('cta_subtitle', models.TextField(blank=True, default='Join thousands of businesses already connecting with the diaspora community. Get listed in minutes.')),
                ('newsletter_title', models.CharField(blank=True, default='Stay Connected', max_length=140)),
                ('newsletter_subtitle', models.TextField(blank=True, default='Featured businesses, global Black events, and diaspora spotlights — no spam, unsubscribe anytime.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Content',
                'verbose_name_plural': 'Home Content',
            },
        ),
    ]
