# Generated by Django 5.0.6 on 2026-07-27 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_seed_stories_news_categories'),
        ('profiles', '0008_alter_companyprofile_verification_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('kind', models.CharField(choices=[('founder_story', 'Founder Story'), ('brand_feature', 'Brand Feature'), ('press_release', 'Press Release')], default='founder_story', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='How long the published story stays featured.')),
                ('subscriber_discount_percent', models.PositiveSmallIntegerField(default=0, help_text='Discount (%) applied when the buyer has an active subscription.')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('features_list', models.JSONField(blank=True, default=list, help_text='Bullet points shown on the package card.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = shown first')),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='StorySubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=12, unique=True)),
                ('kind', models.CharField(choices=[('founder_story', 'Founder Story'), ('brand_feature', 'Brand Feature'), ('press_release', 'Press Release')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='The story text (plain text; paragraphs become blog paragraphs).')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('in_review', 'In review'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending_payment', max_length=16)),
                ('admin_note', models.CharField(blank=True, help_text='Feedback shown to the business (e.g. why it was rejected).', max_length=400)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_submissions', to='profiles.companyprofile')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='promotions.storypackage')),
                ('published_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion', to='blog.blogpost')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stories', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submitted_by', '-created_at'], name='promotions__submitt_f71051_idx'), models.Index(fields=['status'], name='promotions__status_a7f191_idx')],
            },
        ),
    ]
