# Generated by Django 5.0.6 on 2026-07-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
