# Generated by Django 5.0.6 on 2026-07-05 08:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='listing',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='listing',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/og/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
