# Generated by Django 5.0.6 on 2026-07-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_listing_meta_description_listing_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
