# Generated by Django 5.0.6 on 2026-07-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_add_category_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='business_type',
            field=models.CharField(choices=[('product', 'Product-based'), ('service', 'Service-based'), ('both', 'Product & Service'), ('nonprofit', 'Nonprofit / Community')], default='service', help_text='The kind of business — used as a directory filter', max_length=12),
        ),
    ]
