# Generated by Django 5.0.6 on 2026-07-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('homepage', 'Homepage'), ('listing', 'Listing Page'), ('footer', 'Footer'), ('other', 'Other')], default='homepage', max_length=10)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
