# Generated by Django 5.0.6 on 2026-07-26 13:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji or lucide icon name shown with the board.', max_length=40)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = shown first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Forum Category',
                'verbose_name_plural': 'Forum Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('body', models.TextField(help_text='The opening post (plain text).')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned threads sort to the top.')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked threads cannot receive new replies.')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Updated whenever a reply is added — used for ordering.')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='community.forumcategory')),
            ],
            options={
                'ordering': ['-is_pinned', '-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_replies', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.thread')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['-last_activity_at'], name='community_t_last_ac_47e4df_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['category', '-last_activity_at'], name='community_t_categor_fa83fd_idx'),
        ),
    ]
